/** Declaration file generated by dts-gen */

declare module "koa-oauth-server" {    
    export class koa_oauth_server {
        constructor(config: any);
        authorise(): any;
        grant(): any;
    }
    export default koa_oauth_server;
}
